### ISSUE TITLE
Stopping a measurement by pressing 'Enter' raises a ValueError exception

### ISSUE THREAD

**Issue by Jay-Cao123** [ni/measurement-plugin-python#489] opened 2023-10-30 11:12 UTC
# Bug Report

For a measurement that the execution is long, if Press 'Enter' in the command line before the "Stop" button turns to "Start" in the InstrumentStudio, there wold be an Error: _ERROR: Exception iterating responses: Cannot invoke RPC on closed channel!

## Repro or Code Sample

1. Adding a time.sleep() based on the [example code](https://github.com/ni/measurementlink-python/blob/f67e57b7d6d80fcf435c3d3e70be4e4e05050f0a/examples/nidcpower_source_dc_voltage/measurement.py#L85C13-L85C13) to let I can have time to hit the "Enter"
2. Run the measurement
3. Click "Start" button and Press "Enter" before the "Start" button turns to "Stop"
4. Re-run the measurement, there will be another error said that the session has been reserved which seems it has not been destroyed last time
5. Only restart the computer or use Task Manager to terminate the MeasurementLink discovery service can make the measurement run.

## Expected Behavior

After Step3: The Button should be "Stop" and the measurement is aborted correctly.
After Step4: The measurement should be run.

## Current Behavior

After Step3:
![image](https://github.com/ni/measurementlink-python/assets/83160510/4116e353-b5b0-40df-bf5a-fe7d7b1b7ce0)
After Step4:
![image](https://github.com/ni/measurementlink-python/assets/83160510/2ae24b0a-f49d-4b1d-b551-266a69a7985f)

## Context

For a long time execution measurement, it happens likely and will impact the user experience.

## Your Environment

* OS & Device: Windows
* `ni-measurementlink-service` version 1.1.0
* MeasurementLink version 2023Q4
* Python version 3.8 or 3.9

[AB#2566629](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2566629)

**Comment by bkeryan** [comment] 2023-10-31 22:02
I think the cause is that we're closing the gRPC channels in the channel pool before canceling any ongoing server RPCs.

We're calling grpc.Server.stop() with a grace period of 5 seconds before we close the gRPC channel pool. However, stop() returns immediately and the server shutdown continues in another thread. Also, stop() doesn't cancel the RPCs until the grace period expires, so the grace period does't have any benefit for us. stop() returns an event object that we can wait for, but we aren't waiting for it.

**Comment by dixonjoel** [comment] 2024-10-08 19:42
Low ROI

**Closed by dixonjoel** 2024-10-08 19:42 UTC
Labels: bug
